# Generated by Django 5.2.8 on 2025-11-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='barber_photos/', verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('motivo', models.CharField(blank=True, help_text='Opcional (ex: Férias)', max_length=255, null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='core.barberprofile')),
            ],
            options={
                'verbose_name': 'Bloqueio de Data',
                'verbose_name_plural': 'Bloqueios de Datas',
                'ordering': ['data_inicio'],
            },
        ),
    ]
