# Generated by Django 5.2.8 on 2025-11-15 03:58

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barberprofile_profile_picture_bloqueio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='barber_photos/', validators=[core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Foto de Perfil'),
        ),
    ]
