"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import base64
import json
import os
import sys
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
IS_TESTING = any(arg in sys.argv for arg in ('test', 'pytest'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

raw_allowed_hosts = config('ALLOWED_HOSTS', default='')
ALLOWED_HOSTS = [host.strip() for host in raw_allowed_hosts.split(',') if host.strip()]
if DEBUG and not ALLOWED_HOSTS:
    # Em desenvolvimento permitimos localhost automaticamente
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Isso estÃ¡ correto, graÃ§as ao __init__.py
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            # Boa prÃ¡tica para garantir consistÃªncia
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            # Essencial para suportar emojis e caracteres especiais
            'charset': 'utf8mb4', 
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/painel/'

# --- Media and storage configuration ---
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_temp_buffer')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if IS_TESTING:
    GS_BUCKET_NAME = ''
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
    MEDIA_ROOT = os.path.join(BASE_DIR, 'test_media')
    MEDIA_URL = '/media-test/'
else:
    GCS_KEY_FILE = config('GOOGLE_APPLICATION_CREDENTIALS', default='').strip()
    GCS_KEY_JSON = config('GOOGLE_APPLICATION_CREDENTIALS_JSON', default=None)
    GS_BUCKET_NAME = config('GS_BUCKET_NAME')

        # 3. Autentica (CORRIGIDO)
    tmp_credentials_path = None
    if GCS_KEY_JSON:
        try:
            try:
                parsed_credentials = json.loads(GCS_KEY_JSON)
            except json.JSONDecodeError:
                decoded = base64.b64decode(GCS_KEY_JSON)
                parsed_credentials = json.loads(decoded.decode('utf-8'))
        except Exception as exc:
            raise ImproperlyConfigured(
                'GOOGLE_APPLICATION_CREDENTIALS_JSON deve conter JSON válido '
                'ou a string Base64 correspondente.'
            ) from exc

        tmp_dir = BASE_DIR / 'tmp'
        tmp_dir.mkdir(parents=True, exist_ok=True)
        tmp_credentials_path = tmp_dir / 'gcs-key.json'
        tmp_credentials_path.write_text(json.dumps(parsed_credentials), encoding='utf-8')
        GCS_KEY_FILE_PATH = str(tmp_credentials_path)
    elif GCS_KEY_FILE:
        if os.path.isabs(GCS_KEY_FILE):
            GCS_KEY_FILE_PATH = GCS_KEY_FILE
        else:
            GCS_KEY_FILE_PATH = os.path.join(BASE_DIR, GCS_KEY_FILE)
    else:
        raise ImproperlyConfigured(
            'Defina GOOGLE_APPLICATION_CREDENTIALS (caminho) ou ' 
            'GOOGLE_APPLICATION_CREDENTIALS_JSON (conteúdo) para o GCS.'
        )

    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = GCS_KEY_FILE_PATH

    GS_LOCATION = 'media'
    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    GS_FILE_OVERWRITE = False
    GS_DEFAULT_ACL = None
    GS_QUERYSTRING_AUTH = False
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/{GS_LOCATION}/"
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.gcloud.GoogleCloudStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }

# Segurança em produção
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=(0 if DEBUG else 31536000), cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

raw_csrf_origins = config('CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in raw_csrf_origins.split(',') if origin.strip()
]

if IS_TESTING:
    print(">>> ATENÇÃO: Usando banco de dados SQLite IN-MEMORY para testes. <<<")

    # Sobrescreve a configuração do MariaDB
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',  # ':memory:' usa a RAM (super rápido)
    }
